# Generated by Django 6.0.7 on 2026-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_is_scheduled_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='website_url',
            field=models.URLField(blank=True, help_text='Destination URL when recipients click the email button.', max_length=500, null=True),
        ),
    ]
