# Generated by Django 6.0.7 on 2026-07-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={},
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipient',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='recipient',
            table=None,
        ),
    ]
