# Generated by Django 6.0.7 on 2026-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_alter_recipient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
