# Generated by Django 6.0.7 on 2026-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_recipient_is_opened_recipient_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipient',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
